// Client Modal JavaScript - JobNimbus Style

// Use existing API_BASE if defined, otherwise set it
if (typeof window.API_BASE === 'undefined') {
    window.API_BASE = 'http://localhost:3000/api/v1';
}

// Open modal
function openCreateContactModal() {
    const modal = document.getElementById('createContactModal');
    modal.classList.add('show');
    document.body.style.overflow = 'hidden';
    
    // Auto-generate display name
    setupAutoDisplayName();
}

// Close modal
function closeCreateContactModal() {
    const modal = document.getElementById('createContactModal');
    modal.classList.remove('show');
    document.body.style.overflow = '';
    
    // Reset form
    const form = document.getElementById('createContactForm');
    if (form) {
        form.reset();
        // Reset edit mode
        delete form.dataset.editMode;
        delete form.dataset.clientId;
        
        // Reset modal header and button
        const header = modal.querySelector('.modal-header h2');
        const submitBtn = modal.querySelector('.btn-modal-primary');
        if (header) header.textContent = 'Create Contact';
        if (submitBtn) submitBtn.innerHTML = '<i class="fas fa-save"></i> Create Contact';
        
        // Reset display name auto-generation flag
        const displayName = document.getElementById('modalDisplayName');
        if (displayName) {
            displayName.dataset.autoGenerated = 'true';
        }
    }
}

// Setup auto display name generation
function setupAutoDisplayName() {
    const firstName = document.getElementById('modalFirstName');
    const lastName = document.getElementById('modalLastName');
    const company = document.getElementById('modalCompany');
    const displayName = document.getElementById('modalDisplayName');
    
    function updateDisplayName() {
        const first = firstName.value.trim();
        const last = lastName.value.trim();
        const comp = company.value.trim();
        
        if (displayName.value === '' || displayName.dataset.autoGenerated === 'true') {
            if (comp) {
                displayName.value = comp;
            } else if (first || last) {
                displayName.value = `${first} ${last}`.trim();
            }
            displayName.dataset.autoGenerated = 'true';
        }
    }
    
    firstName.addEventListener('input', updateDisplayName);
    lastName.addEventListener('input', updateDisplayName);
    company.addEventListener('input', updateDisplayName);
    displayName.addEventListener('input', () => {
        displayName.dataset.autoGenerated = 'false';
    });
}

// Submit form
async function submitCreateContact() {
    const form = document.getElementById('createContactForm');
    const formData = new FormData(form);
    
    // Check if we're in edit mode
    const isEditMode = form.dataset.editMode === 'true';
    const clientId = form.dataset.clientId;
    
    // Convert FormData to object
    const data = {
        first_name: formData.get('firstName') || null,
        last_name: formData.get('lastName') || null,
        display_name: formData.get('displayName'),
        company: formData.get('company') || null,
        email: formData.get('email') || null,
        website: formData.get('website') || null,
        main_phone: formData.get('mainPhone') || null,
        mobile_phone: formData.get('mobilePhone') || null,
        work_phone: formData.get('workPhone') || null,
        fax: formData.get('fax') || null,
        address_line_1: formData.get('addressLine1') || null,
        address_line_2: formData.get('addressLine2') || null,
        city: formData.get('city') || null,
        state: formData.get('state') || null,
        postal_code: formData.get('postalCode') || null,
        industry: formData.get('industryType') || null,
        status: 'Lead',
        custom_fields: JSON.stringify({})
    };
    
    try {
        const submitBtn = document.querySelector('.btn-modal-primary');
        const originalText = submitBtn.innerHTML;
        submitBtn.disabled = true;
        submitBtn.innerHTML = isEditMode 
            ? '<i class="fas fa-spinner fa-spin"></i> Updating...'
            : '<i class="fas fa-spinner fa-spin"></i> Creating...';
        
        const url = isEditMode ? `${window.API_BASE}/contacts/${clientId}` : `${window.API_BASE}/contacts/`;
        const method = isEditMode ? 'PUT' : 'POST';
        
        const response = await fetch(url, {
            method: method,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(data)
        });
        
        if (!response.ok) {
            const error = await response.json();
            throw new Error(error.error || `Failed to ${isEditMode ? 'update' : 'create'} contact`);
        }
        
        const result = await response.json();
        
        // Close modal and reload clients list
        closeCreateContactModal();
        
        // Show success message
        alert(`Contact ${isEditMode ? 'updated' : 'created'} successfully!`);
        
        // Reload the clients list
        if (typeof loadClients === 'function') {
            loadClients();
        } else {
            window.location.reload();
        }
    } catch (error) {
        console.error(`Error ${isEditMode ? 'updating' : 'creating'} contact:`, error);
        alert(`Error ${isEditMode ? 'updating' : 'creating'} contact: ` + error.message);
        
        const submitBtn = document.querySelector('.btn-modal-primary');
        submitBtn.disabled = false;
        submitBtn.innerHTML = isEditMode 
            ? '<i class="fas fa-save"></i> Update Contact'
            : '<i class="fas fa-save"></i> Create Contact';
    }
}

// Select tags (placeholder)
function selectTags() {
    alert('Tag selection coming soon!');
}

// Close modal on overlay click
document.addEventListener('click', function(e) {
    const modal = document.getElementById('createContactModal');
    if (e.target === modal) {
        closeCreateContactModal();
    }
});

// Close modal on Escape key
document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') {
        const modal = document.getElementById('createContactModal');
        if (modal && modal.classList.contains('show')) {
            closeCreateContactModal();
        }
    }
});

// Make functions globally available
window.openCreateContactModal = openCreateContactModal;
window.closeCreateContactModal = closeCreateContactModal;
window.submitCreateContact = submitCreateContact;

