// Enhanced Client Form JavaScript

const API_BASE = 'http://localhost:3000/api/v1';
let fieldDefinitions = [];

// Toggle section collapse
function toggleSection(button) {
    const section = button.closest('.form-section');
    const content = section.querySelector('.section-content');
    const icon = button.querySelector('i');
    
    section.classList.toggle('collapsed');
    
    if (section.classList.contains('collapsed')) {
        icon.classList.remove('fa-chevron-down');
        icon.classList.add('fa-chevron-up');
    } else {
        icon.classList.remove('fa-chevron-up');
        icon.classList.add('fa-chevron-down');
    }
}

// Update progress bar
function updateProgress() {
    const sections = document.querySelectorAll('.form-section[data-section]');
    const filledSections = Array.from(sections).filter(section => {
        const inputs = section.querySelectorAll('input[required], select[required]');
        return Array.from(inputs).some(input => input.value.trim() !== '');
    }).length;
    
    const totalSections = sections.length;
    const progress = (filledSections / totalSections) * 100;
    
    document.getElementById('progressBar').style.width = `${progress}%`;
    
    // Update step indicators
    sections.forEach((section, index) => {
        const stepNum = parseInt(section.dataset.section);
        const step = document.querySelector(`[data-step="${stepNum}"]`);
        if (step) {
            const inputs = section.querySelectorAll('input[required], select[required]');
            const hasValue = Array.from(inputs).some(input => input.value.trim() !== '');
            
            if (hasValue) {
                step.classList.add('completed');
                step.classList.remove('active');
            } else if (index === filledSections) {
                step.classList.add('active');
                step.classList.remove('completed');
            } else {
                step.classList.remove('active', 'completed');
            }
        }
    });
}

// Scroll progress indicator
function updateScrollProgress() {
    const windowHeight = window.innerHeight;
    const documentHeight = document.documentElement.scrollHeight;
    const scrollTop = window.pageYOffset || document.documentElement.scrollTop;
    const scrollPercent = (scrollTop / (documentHeight - windowHeight)) * 100;
    
    document.getElementById('scrollProgress').style.width = `${scrollPercent}%`;
}

// Initialize enhanced features
document.addEventListener('DOMContentLoaded', async () => {
    await loadFieldDefinitions();
    renderCustomFields();
    setupFormHandler();
    setupAutoDisplayName();
    
    // Add event listeners for progress tracking
    const inputs = document.querySelectorAll('input, select, textarea');
    inputs.forEach(input => {
        input.addEventListener('input', updateProgress);
        input.addEventListener('change', updateProgress);
    });
    
    // Scroll progress
    window.addEventListener('scroll', updateScrollProgress);
    updateScrollProgress();
    updateProgress();
});

// Load field definitions on page load
document.addEventListener('DOMContentLoaded', async () => {
    await loadFieldDefinitions();
    renderCustomFields();
    setupFormHandler();
    setupAutoDisplayName();
});

// Auto-generate display name
function setupAutoDisplayName() {
    const firstName = document.getElementById('firstName');
    const lastName = document.getElementById('lastName');
    const company = document.getElementById('company');
    const displayName = document.getElementById('displayName');
    
    function updateDisplayName() {
        const first = firstName.value.trim();
        const last = lastName.value.trim();
        const comp = company.value.trim();
        
        if (displayName.value === '' || displayName.dataset.autoGenerated === 'true') {
            if (comp) {
                displayName.value = comp;
            } else if (first || last) {
                displayName.value = `${first} ${last}`.trim();
            }
            displayName.dataset.autoGenerated = 'true';
        }
    }
    
    firstName.addEventListener('input', updateDisplayName);
    lastName.addEventListener('input', updateDisplayName);
    company.addEventListener('input', updateDisplayName);
    displayName.addEventListener('input', () => {
        displayName.dataset.autoGenerated = 'false';
    });
}

// Load field definitions
async function loadFieldDefinitions() {
    try {
        const response = await fetch(`${API_BASE}/contact-fields/`);
        if (!response.ok) throw new Error('Failed to load field definitions');
        
        fieldDefinitions = await response.json();
    } catch (error) {
        console.error('Error loading field definitions:', error);
    }
}

// Render custom fields grouped by section
function renderCustomFields() {
    const container = document.getElementById('customFieldsContainer');
    if (fieldDefinitions.length === 0) {
        container.innerHTML = '<p style="color: #64748b;">No custom fields defined. Go to Settings to add custom fields.</p>';
        return;
    }
    
    // Group fields by section
    const sections = {
        basic: [],
        contact_details: [],
        custom: [],
        industry_specific: []
    };
    
    fieldDefinitions.forEach(field => {
        if (sections[field.section]) {
            sections[field.section].push(field);
        } else {
            sections.custom.push(field);
        }
    });
    
    // Render sections
    Object.keys(sections).forEach(sectionKey => {
        const sectionFields = sections[sectionKey];
        if (sectionFields.length === 0) return;
        
        const sectionDiv = document.createElement('div');
        sectionDiv.className = 'custom-fields-subsection';
        sectionDiv.innerHTML = `<h3 class="subsection-title">${formatSectionTitle(sectionKey)}</h3>`;
        
        const fieldsContainer = document.createElement('div');
        fieldsContainer.className = 'custom-fields-grid';
        
        sectionFields.forEach(field => {
            const fieldElement = createFieldElement(field);
            fieldsContainer.appendChild(fieldElement);
        });
        
        sectionDiv.appendChild(fieldsContainer);
        container.appendChild(sectionDiv);
    });
}

// Format section title
function formatSectionTitle(section) {
    const titles = {
        basic: 'Basic Information',
        contact_details: 'Contact Details',
        custom: 'Custom Fields',
        industry_specific: 'Industry Specific'
    };
    return titles[section] || section.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

// Create field element based on field type
function createFieldElement(field) {
    const groupDiv = document.createElement('div');
    groupDiv.className = 'form-group';
    groupDiv.dataset.fieldKey = field.field_key;
    
    const label = document.createElement('label');
    label.htmlFor = `field_${field.field_key}`;
    label.innerHTML = `${field.name}${field.is_required ? ' <span class="required">*</span>' : ''}`;
    
    let inputElement;
    
    switch (field.field_type) {
        case 'textarea':
            inputElement = document.createElement('textarea');
            inputElement.rows = 4;
            break;
        case 'dropdown':
            inputElement = document.createElement('select');
            if (field.options && Array.isArray(field.options)) {
                inputElement.innerHTML = '<option value="">Select...</option>' +
                    field.options.map(opt => `<option value="${escapeHtml(opt)}">${escapeHtml(opt)}</option>`).join('');
            }
            break;
        case 'multiselect':
            groupDiv.className += ' checkbox-group-container';
            const checkboxGroup = document.createElement('div');
            checkboxGroup.className = 'checkbox-group';
            if (field.options && Array.isArray(field.options)) {
                field.options.forEach(option => {
                    const checkboxItem = document.createElement('div');
                    checkboxItem.className = 'checkbox-item';
                    checkboxItem.innerHTML = `
                        <input type="checkbox" id="field_${field.field_key}_${option}" 
                               name="${field.field_key}[]" value="${escapeHtml(option)}">
                        <label for="field_${field.field_key}_${option}">${escapeHtml(option)}</label>
                    `;
                    checkboxGroup.appendChild(checkboxItem);
                });
            }
            groupDiv.appendChild(label);
            groupDiv.appendChild(checkboxGroup);
            if (field.help_text) {
                const helpText = document.createElement('small');
                helpText.className = 'form-hint';
                helpText.textContent = field.help_text;
                groupDiv.appendChild(helpText);
            }
            return groupDiv;
        case 'boolean':
            groupDiv.className += ' checkbox-container';
            const checkbox = document.createElement('div');
            checkbox.className = 'checkbox-item';
            checkbox.innerHTML = `
                <input type="checkbox" id="field_${field.field_key}" name="${field.field_key}">
                <label for="field_${field.field_key}">${field.name}${field.is_required ? ' <span class="required">*</span>' : ''}</label>
            `;
            groupDiv.appendChild(checkbox);
            if (field.help_text) {
                const helpText = document.createElement('small');
                helpText.className = 'form-hint';
                helpText.textContent = field.help_text;
                groupDiv.appendChild(helpText);
            }
            return groupDiv;
        default:
            inputElement = document.createElement('input');
            inputElement.type = getInputType(field.field_type);
    }
    
    inputElement.id = `field_${field.field_key}`;
    inputElement.name = field.field_key;
    if (field.placeholder) inputElement.placeholder = field.placeholder;
    if (field.is_required) inputElement.required = true;
    
    groupDiv.appendChild(label);
    groupDiv.appendChild(inputElement);
    
    if (field.help_text) {
        const helpText = document.createElement('small');
        helpText.className = 'form-hint';
        helpText.textContent = field.help_text;
        groupDiv.appendChild(helpText);
    }
    
    return groupDiv;
}

// Get input type based on field type
function getInputType(fieldType) {
    const typeMap = {
        text: 'text',
        number: 'number',
        date: 'date',
        datetime: 'datetime-local',
        email: 'email',
        phone: 'tel',
        url: 'url'
    };
    return typeMap[fieldType] || 'text';
}

// Setup form handler
function setupFormHandler() {
    document.getElementById('clientForm').addEventListener('submit', async (e) => {
        e.preventDefault();
        
        const formData = {
            // Basic Information
            first_name: document.getElementById('firstName').value,
            last_name: document.getElementById('lastName').value,
            display_name: document.getElementById('displayName').value,
            company: document.getElementById('company').value || null,
            
            // Contact Details
            email: document.getElementById('email').value || null,
            website: document.getElementById('website').value || null,
            main_phone: document.getElementById('mainPhone').value || null,
            mobile_phone: document.getElementById('mobilePhone').value || null,
            
            // Address
            address_line_1: document.getElementById('addressLine1').value || null,
            address_line_2: document.getElementById('addressLine2').value || null,
            city: document.getElementById('city').value || null,
            state: document.getElementById('state').value || null,
            postal_code: document.getElementById('postalCode').value || null,
            country: document.getElementById('country').value || null,
            
            // Business Details
            client_type: document.getElementById('clientType').value || null,
            industry: document.getElementById('industry').value || null,
            status: document.getElementById('status').value,
            lead_source: document.getElementById('leadSource').value || null,
            description: document.getElementById('description').value || null,
            notes: document.getElementById('notes').value || null,
            
            // Website Design
            current_website_url: document.getElementById('currentWebsiteUrl').value || null,
            current_website_platform: document.getElementById('currentWebsitePlatform').value || null,
            website_goals: document.getElementById('websiteGoals').value || null,
            target_audience: document.getElementById('targetAudience').value || null,
            brand_colors: document.getElementById('brandColors').value ? 
                JSON.stringify(document.getElementById('brandColors').value.split(',').map(c => c.trim())) : null,
            brand_fonts: document.getElementById('brandFonts').value ? 
                JSON.stringify(document.getElementById('brandFonts').value.split(',').map(f => f.trim())) : null,
            brand_guidelines_url: document.getElementById('brandGuidelinesUrl').value || null,
            project_budget_range: document.getElementById('projectBudgetRange').value || null,
            timeline_preference: document.getElementById('timelinePreference').value || null,
            
            // Social Media
            social_media_platforms: JSON.stringify(
                Array.from(document.querySelectorAll('input[name="socialPlatforms[]"]:checked')).map(cb => cb.value)
            ),
            content_goals: document.getElementById('contentGoals').value || null,
            posting_frequency_preference: document.getElementById('postingFrequency').value || null,
            content_style_preference: document.getElementById('contentStyle').value || null,
            brand_voice_description: document.getElementById('brandVoice').value || null,
            
            // Communication
            preferred_communication_method: document.getElementById('preferredCommunication').value || null,
            
            // Custom Fields
            custom_fields: {}
        };
        
        // Collect custom fields
        fieldDefinitions.forEach(field => {
            const fieldKey = field.field_key;
            let value;
            
            if (field.field_type === 'multiselect') {
                const checkboxes = document.querySelectorAll(`input[name="${fieldKey}[]"]:checked`);
                value = Array.from(checkboxes).map(cb => cb.value);
                if (value.length > 0) {
                    formData.custom_fields[fieldKey] = value;
                }
            } else if (field.field_type === 'boolean') {
                const checkbox = document.getElementById(`field_${fieldKey}`);
                formData.custom_fields[fieldKey] = checkbox ? checkbox.checked : false;
            } else {
                const input = document.getElementById(`field_${fieldKey}`);
                if (input && input.value) {
                    formData.custom_fields[fieldKey] = input.value;
                }
            }
        });
        
        // Convert custom_fields to JSON string
        formData.custom_fields = JSON.stringify(formData.custom_fields);
        
        try {
            const submitBtn = document.querySelector('button[type="submit"]');
            const originalText = submitBtn.innerHTML;
            submitBtn.disabled = true;
            submitBtn.innerHTML = '<i class="fas fa-spinner fa-spin"></i> Creating Client...';
            
            const response = await fetch(`${API_BASE}/contacts/`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(formData)
            });
            
            if (!response.ok) {
                const error = await response.json();
                throw new Error(error.error || 'Failed to create client');
            }
            
            const result = await response.json();
            alert('Client created successfully!');
            window.location.href = `/clients/${result.id}`;
        } catch (error) {
            console.error('Error creating client:', error);
            alert('Error creating client: ' + error.message);
            document.querySelector('button[type="submit"]').disabled = false;
            document.querySelector('button[type="submit"]').innerHTML = '<i class="fas fa-save"></i> Create Client';
        }
    });
}

// Escape HTML
function escapeHtml(text) {
    if (!text) return '';
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

